version: '3.7'

services:
    reptilian-cli-dev:
        build:
            context: .
        working_dir: /app
        volumes: 
            - ..:/app
        command: sleep infinity
        # command runs after build
        # sleep infinity will keep the container alive until we choose to stop it