version: '3.7'

services:
    reptilian-cli-dev:
        build:
            context: .
        depends_on:
            - db
        working_dir: /app
        volumes: 
            - ..:/app
        command: bash -c "pwsh /app/.devcontainer/init.ps1 && sleep infinity"
        # command runs after build
        # sleep infinity will keep the container alive until we choose to stop it

    db:
        image: mcr.microsoft.com/mssql/server
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Pa55word!
        ports: 
            - 9876:1433